-- AlterTable
ALTER TABLE `Product` ADD COLUMN `category` ENUM('ALL', 'SPRING', 'SUMMER', 'AUTUMN', 'WINTER', 'ROMANTIC', 'SYMPATHY', 'CONGRATULATION', 'TROPIC', 'ANNIVERSARY', 'BOUQUETS', 'BASKET', 'VASE') NOT NULL DEFAULT 'ALL';

-- CreateTable
CREATE TABLE `Tags` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `productId` INTEGER NOT NULL,
    `tagName` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Tags` ADD CONSTRAINT `Tags_productId_fkey` FOREIGN KEY (`productId`) REFERENCES `Product`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
