name: admin Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'admin/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build Next.js server
        run: |
          cd admin
          npm install
          npm run build

      - name: Transfer files to EC2 admin
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_LOCAL }}
          source: "admin/"
          target: "/flowerbox/admin/"

      - name: SSH into EC2 and restart Next.js admin
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_LOCAL }}
          script: |
            source ~/.nvm/nvm.sh
            /home/***/.nvm/versions/node/v20.11.1/bin/pm2 restart admin
