name: Server Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build Node.js server
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PORT: 4000
          BYCRYPT_SALT: ${{ secrets.SALT }}
          SECRET_KEY: ${{ secrets.JWT_SECRET }}
          IAM_ACCESS_KEY_ID: ${{ secrets.IAM_ACCESS_KEY_ID }}
          IAM_SECRET_KEY_ID: ${{ secrets.IAM_SECRET_KEY_ID }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CLIENT_SERVER: https://admin.flower.box
          CLIENT_SERVER_2: https://www.flower.box
          COOKIE_CLIENT: .flower.box
        run: |
          cd server
          npm install
          cd src
          npx prisma migrate deploy
          npx prisma generate

      - name: build app    
        run: npm run build
        env: 
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PORT: 4000
          BYCRYPT_SALT: ${{ secrets.SALT }}
          SECRET_KEY: ${{ secrets.JWT_SECRET }}
          IAM_ACCESS_KEY_ID: ${{ secrets.IAM_ACCESS_KEY_ID }}
          IAM_SECRET_KEY_ID: ${{ secrets.IAM_SECRET_KEY_ID }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DEV_STRIPE_SECRECT: ${{ secrets.DEV_STRIPE_SECRECT }}
          CLIENT_SERVER: https://admin.flower.box
          CLIENT_SERVER_2: https://www.flower.box
          COOKIE_CLIENT: .flower.box
          
        
      - name: Transfer files to EC2 server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_LOCAL }}
          source: "server/"
          target: "/flowerbox/"

      - name: SSH into EC2 and restart Node.js server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY_LOCAL }}
          script: |
            source ~/.nvm/nvm.sh
            export NODE_ENV=production
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            export PORT=4000
            export BYCRYPT_SALT=${{ secrets.SALT }}
            export SECRET_KEY=${{ secrets.JWT_SECRET }}
            export IAM_ACCESS_KEY_ID=${{ secrets.IAM_ACCESS_KEY_ID }}
            export IAM_SECRET_KEY_ID=${{ secrets.IAM_SECRET_KEY_ID }}
            export AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}
            export AWS_REGION=${{ secrets.AWS_REGION }}
            export DEV_STRIPE_SECRECT=${{ secrets.DEV_STRIPE_SECRECT }}
            export CLIENT_SERVER=https://admin.flower.box
            export CLIENT_SERVER_2=https://www.flower.box
            export COOKIE_CLIENT=.flower.box
            /home/*/.nvm/versions/node/v20.11.1/bin/pm2 restart index